"""Run state, budgets, stopping rules, and persistence."""

from llm_alpha_mining.mining.orchestration.budget import (
    BudgetController,
    BudgetExceeded,
    BudgetLimits,
    BudgetUsage,
)
from llm_alpha_mining.mining.orchestration.campaign import (
    CampaignConfig,
    CampaignEngine,
    CampaignEngineError,
    CampaignRoundResult,
    CampaignStopped,
    RejectedProposal,
)
from llm_alpha_mining.mining.orchestration.hypotheses import (
    HypothesisEntry,
    HypothesisRegistry,
    HypothesisRegistryError,
    semantic_signal_hash,
)
from llm_alpha_mining.mining.orchestration.pareto import (
    DEFAULT_PARETO_OBJECTIVES,
    PARETO_CHECKPOINT_SCHEMA,
    PARETO_LEDGER_SCHEMA,
    DiverseShortlist,
    FrontierSnapshot,
    ObjectiveDirection,
    ParetoCheckpoint,
    ParetoGovernanceError,
    ParetoLedgerEntry,
    ParetoObjective,
    ParetoObjectiveSpec,
    ParetoObservation,
    ParetoObservationLedger,
    ParetoRoundObservation,
    ParetoStopController,
    ParetoStoppingConfig,
    ParetoStoppingDecision,
    ShortlistRejection,
    build_campaign_frontier,
    build_round_frontier,
    epsilon_dominates,
    epsilon_equivalent,
    frontier_progressed,
    objective_specs_hash,
    objective_specs_with_epsilon,
    pareto_frontier,
    select_diverse_shortlist,
)
from llm_alpha_mining.mining.orchestration.repository import (
    EventRecord,
    SQLiteRepository,
)
from llm_alpha_mining.mining.orchestration.state import InvalidStateTransition

# workspace_campaign imports the protocol loader.  These names are resolved
# lazily below so importing ``llm_alpha_mining.mining.protocol`` cannot recurse
# through this package initializer.
_WORKSPACE_EXPORTS = frozenset(
    {
        "CampaignCheckpoint",
        "ReplayRegistrationResult",
        "SanitizedFeedbackBatch",
        "WorkspaceBranchBinding",
        "WorkspaceCampaignError",
        "load_campaign_checkpoint",
        "load_sanitized_feedback_batch",
        "load_sanitized_feedback_jsonl",
        "register_replay_generation",
        "validate_workspace_branch",
        "validate_sanitized_feedback_bindings",
    }
)


def __getattr__(name: str):
    if name in _WORKSPACE_EXPORTS:
        from llm_alpha_mining.mining.orchestration import workspace_campaign

        return getattr(workspace_campaign, name)
    raise AttributeError(name)


__all__ = [
    "BudgetController",
    "BudgetExceeded",
    "BudgetLimits",
    "BudgetUsage",
    "CampaignConfig",
    "CampaignEngine",
    "CampaignEngineError",
    "CampaignRoundResult",
    "CampaignStopped",
    "CampaignCheckpoint",
    "EventRecord",
    "HypothesisEntry",
    "HypothesisRegistry",
    "HypothesisRegistryError",
    "DEFAULT_PARETO_OBJECTIVES",
    "PARETO_CHECKPOINT_SCHEMA",
    "PARETO_LEDGER_SCHEMA",
    "DiverseShortlist",
    "FrontierSnapshot",
    "ObjectiveDirection",
    "ParetoCheckpoint",
    "ParetoGovernanceError",
    "ParetoLedgerEntry",
    "ParetoObjective",
    "ParetoObjectiveSpec",
    "ParetoObservation",
    "ParetoObservationLedger",
    "ParetoRoundObservation",
    "ParetoStopController",
    "ParetoStoppingConfig",
    "ParetoStoppingDecision",
    "ShortlistRejection",
    "InvalidStateTransition",
    "RejectedProposal",
    "ReplayRegistrationResult",
    "SanitizedFeedbackBatch",
    "WorkspaceBranchBinding",
    "SQLiteRepository",
    "WorkspaceCampaignError",
    "load_campaign_checkpoint",
    "load_sanitized_feedback_batch",
    "load_sanitized_feedback_jsonl",
    "register_replay_generation",
    "build_campaign_frontier",
    "build_round_frontier",
    "epsilon_dominates",
    "epsilon_equivalent",
    "frontier_progressed",
    "objective_specs_hash",
    "objective_specs_with_epsilon",
    "pareto_frontier",
    "select_diverse_shortlist",
    "semantic_signal_hash",
    "validate_sanitized_feedback_bindings",
    "validate_workspace_branch",
]
from llm_alpha_mining.mining.orchestration.evaluation_attempts import (
    ATTEMPT_STORE_SCHEMA_VERSION,
    CHECKPOINT_STAGES,
    AttemptBudgetExceeded,
    AttemptLeaseConflict,
    AttemptRecord,
    AttemptStatus,
    AttemptUsage,
    CheckpointRecord,
    EvaluationAttemptError,
    EvaluationAttemptStore,
    completed_candidate_ids,
)
from llm_alpha_mining.mining.orchestration.feedback import (
    SANITIZED_FEEDBACK_BATCH_SCHEMA,
    FeedbackBatch,
    FeedbackBuildError,
    build_feedback_batch,
    load_gate_decisions_jsonl,
    write_feedback_batch,
)
from llm_alpha_mining.mining.orchestration.generation_executor import (
    CandidateExecutionStatus,
    CandidateExecutionSummary,
    CandidateStateBridge,
    CandidateStateEvent,
    CandidateStateEventType,
    CheckpointIntegrityError,
    GenerationCandidate,
    GenerationExecutionError,
    GenerationExecutionSummary,
    ResumableGenerationExecutor,
    StageArtifact,
    StageExecutionContext,
    StageRunner,
    SuccessfulAttemptBindingError,
    VerifiedStageArtifact,
)
from llm_alpha_mining.mining.orchestration.campaign_close_fdr import (
    ATTEMPT_COLLAPSE_POLICY,
    CAMPAIGN_CLOSE_FDR_FAMILY_DEFINITION,
    CAMPAIGN_CLOSE_FDR_INTERPRETATION,
    CAMPAIGN_CLOSE_FDR_REPORT_SCHEMA,
    CAMPAIGN_CLOSE_FDR_REQUEST_SCHEMA,
    CAMPAIGN_CLOSE_FDR_ROLE,
    FAILED_TEST_POLICY,
    CampaignCloseFDRError,
    CampaignCloseFDRReport,
    CampaignCloseFDRRequest,
    CampaignCloseHypothesisResult,
    FrozenHypothesis,
    PrimaryTestAttempt,
    TerminalAttemptStatus,
    benjamini_hochberg_complete_family,
    build_campaign_close_fdr_report,
    load_campaign_close_fdr_report,
    report_results_by_candidate,
    verify_campaign_close_fdr_report,
    write_campaign_close_fdr_report,
)
from llm_alpha_mining.mining.orchestration.campaign_attempt_ledger import (
    CAMPAIGN_ATTEMPT_CHECKPOINT_SCHEMA,
    CAMPAIGN_ATTEMPT_LEDGER_SCHEMA,
    CAMPAIGN_LEDGER_SEAL_RECEIPT_SCHEMA,
    CHILD_ATTEMPT_LOGICAL_STATE_SCHEMA,
    CHILD_ATTEMPT_SNAPSHOT_SCHEMA,
    DEFAULT_CAMPAIGN_ATTEMPT_BUDGET,
    CampaignAttemptBudgetExceeded,
    CampaignAttemptCheckpoint,
    CampaignAttemptConflict,
    CampaignAttemptLedger,
    CampaignAttemptLedgerError,
    CampaignAttemptLedgerSealed,
    CampaignAttemptStatus,
    CampaignAttemptUsage,
    CampaignReservation,
    CampaignLedgerSealReceipt,
    ChildAttemptSnapshot,
    ChildSnapshotIntegrityError,
    ReconcileResult,
    import_child_workspace_snapshot,
    load_campaign_attempt_checkpoint,
    load_campaign_ledger_seal_receipt,
    load_sealed_campaign_ledger_snapshot,
    write_campaign_attempt_checkpoint,
)

__all__ += [
    "ATTEMPT_STORE_SCHEMA_VERSION",
    "CHECKPOINT_STAGES",
    "AttemptBudgetExceeded",
    "AttemptLeaseConflict",
    "AttemptRecord",
    "AttemptStatus",
    "AttemptUsage",
    "CheckpointRecord",
    "EvaluationAttemptError",
    "EvaluationAttemptStore",
    "completed_candidate_ids",
    "SANITIZED_FEEDBACK_BATCH_SCHEMA",
    "FeedbackBatch",
    "FeedbackBuildError",
    "build_feedback_batch",
    "load_gate_decisions_jsonl",
    "write_feedback_batch",
    "CandidateExecutionStatus",
    "CandidateExecutionSummary",
    "CandidateStateBridge",
    "CandidateStateEvent",
    "CandidateStateEventType",
    "CheckpointIntegrityError",
    "GenerationCandidate",
    "GenerationExecutionError",
    "GenerationExecutionSummary",
    "ResumableGenerationExecutor",
    "StageArtifact",
    "StageExecutionContext",
    "StageRunner",
    "SuccessfulAttemptBindingError",
    "VerifiedStageArtifact",
    "ATTEMPT_COLLAPSE_POLICY",
    "CAMPAIGN_CLOSE_FDR_FAMILY_DEFINITION",
    "CAMPAIGN_CLOSE_FDR_INTERPRETATION",
    "CAMPAIGN_CLOSE_FDR_REPORT_SCHEMA",
    "CAMPAIGN_CLOSE_FDR_REQUEST_SCHEMA",
    "CAMPAIGN_CLOSE_FDR_ROLE",
    "FAILED_TEST_POLICY",
    "CampaignCloseFDRError",
    "CampaignCloseFDRReport",
    "CampaignCloseFDRRequest",
    "CampaignCloseHypothesisResult",
    "FrozenHypothesis",
    "PrimaryTestAttempt",
    "TerminalAttemptStatus",
    "benjamini_hochberg_complete_family",
    "build_campaign_close_fdr_report",
    "load_campaign_close_fdr_report",
    "report_results_by_candidate",
    "verify_campaign_close_fdr_report",
    "write_campaign_close_fdr_report",
    "CAMPAIGN_ATTEMPT_CHECKPOINT_SCHEMA",
    "CAMPAIGN_ATTEMPT_LEDGER_SCHEMA",
    "CAMPAIGN_LEDGER_SEAL_RECEIPT_SCHEMA",
    "CHILD_ATTEMPT_LOGICAL_STATE_SCHEMA",
    "CHILD_ATTEMPT_SNAPSHOT_SCHEMA",
    "DEFAULT_CAMPAIGN_ATTEMPT_BUDGET",
    "CampaignAttemptBudgetExceeded",
    "CampaignAttemptCheckpoint",
    "CampaignAttemptConflict",
    "CampaignAttemptLedger",
    "CampaignAttemptLedgerError",
    "CampaignAttemptLedgerSealed",
    "CampaignAttemptStatus",
    "CampaignAttemptUsage",
    "CampaignReservation",
    "CampaignLedgerSealReceipt",
    "ChildAttemptSnapshot",
    "ChildSnapshotIntegrityError",
    "ReconcileResult",
    "import_child_workspace_snapshot",
    "load_campaign_attempt_checkpoint",
    "load_campaign_ledger_seal_receipt",
    "load_sealed_campaign_ledger_snapshot",
    "write_campaign_attempt_checkpoint",
]
